### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by xuan-ma** [roboartisan-term/robosdk#5]
在代理环境下有问题：FileOps.download从OBS下载文件会一直卡在那里

![image](https://user-images.githubusercontent.com/52165155/213066654-925a50a1-4cbc-455b-b1d0-532dd2de6b55.png)

**Comment by JoeyHwong-gk** [comment]
Thank you for your contribution, we've fixed by #6 .

Note:

Use the system proxy:

```bash
 export FILE_TRANS_PROXY="True"; export http_proxy="http://your_user:your_password@your_proxy_url:your_proxy_port"
```

Use the specified proxy:

```bash
 export FILE_TRANS_PROXY="http://your_user:your_password@your_proxy_url:your_proxy_port"
```

**Comment by xuan-ma** [comment]
已解决，谢谢！！！

**Comment by JoeyHwong-gk** [comment]
Thanks for the feedback
